name: localtweetcast
dependencies:
- flask=0.10.1=py27_1
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_0
- markupsafe=0.23=py27_0
- openssl=1.0.2g=0
- pip=8.1.1=py27_1
- python=2.7.11=0
- readline=6.2=2
- setuptools=20.6.7=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- werkzeug=0.11.5=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - boto==2.39.0
  - bz2file==0.98
  - certifi==2016.2.28
  - elasticsearch==1.9.0
  - gensim==0.12.4
  - httpretty==0.8.10
  - numpy==1.11.0
  - oauthlib==1.0.3
  - pyelasticsearch==1.4
  - pymongo==3.2.2
  - python-twitter==2.2
  - requests==2.8.1
  - requests-oauthlib==0.6.1
  - scipy==0.17.0
  - simplejson==3.8.2
  - six==1.10.0
  - smart-open==1.3.2
  - tweepy==3.5.0
  - urllib3==1.15.1

